apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: prod-db-secret
      containers:
        - name: sample-node-app
          image: davidbroderickabazantum/node-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: sample-node-app
  ports:
    - port: 80
      targetPort: 8000

